### ISSUE TITLE
Final changes needed

### ISSUE THREAD

**Issue by akshitadixit** [GDSC-IIIT-Kalyani/Student-Portfolio#3]
* Remove navbar, will confuse kids rn
* Add lorem ipsum dummy with `<p></p>` tags
* @Suryanshomar7240 comments in the code?? -_-
* Remove projects and experience sections, freshers don't need it

**Comment by Suryanshomar7240** [comment]
yeah doing

**Comment by Suryanshomar7240** [comment]
All changes are applied so closing this issue :)
